name = "personal-finance-app"
pages_build_output_dir = "./dist"
compatibility_date = "2024-10-06"

[[kv_namespaces]]
binding = "KV"
id = "b2fa876049cd47e1b6cab8e44676cd49"

[[env.production.kv_namespaces]]
binding = "KV"
id = "7deefaec11ff4001960cca3cb917c879"
